import type { ProviderId, ProviderConfig } from "./types/provider.js";

export const API_VERSION = "v1";
export const DEFAULT_PORT = 3000;
export const WS_PING_INTERVAL = 30_000;
export const SESSION_OUTPUT_BUFFER_MS = 16; // ~60fps debounce
export const MAX_SCROLLBACK_LINES = 1000;

export const PROVIDERS: Record<ProviderId, ProviderConfig> = {
  "claude-code": {
    id: "claude-code",
    name: "claude-code",
    displayName: "Claude Code",
    icon: "anthropic",
    models: [
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        contextWindow: 200_000,
        maxOutput: 128_000,
        costPer1kInput: 0.005,
        costPer1kOutput: 0.025,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        contextWindow: 200_000,
        maxOutput: 64_000,
        costPer1kInput: 0.003,
        costPer1kOutput: 0.015,
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        contextWindow: 200_000,
        maxOutput: 64_000,
        costPer1kInput: 0.001,
        costPer1kOutput: 0.005,
      },
    ],
    defaultModel: "claude-sonnet-4-6",
    requiresApiKey: false,
    installCommand: "npm install -g @anthropic-ai/claude-code",
    checkCommand: "claude --version",
  },
  "openai-codex": {
    id: "openai-codex",
    name: "openai-codex",
    displayName: "OpenAI Codex CLI",
    icon: "openai",
    models: [
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        contextWindow: 200_000,
        maxOutput: 128_000,
        costPer1kInput: 0.00175,
        costPer1kOutput: 0.014,
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        contextWindow: 200_000,
        maxOutput: 128_000,
        costPer1kInput: 0.00175,
        costPer1kOutput: 0.014,
      },
      {
        id: "o4-mini",
        name: "o4-mini",
        contextWindow: 200_000,
        maxOutput: 100_000,
        costPer1kInput: 0.0011,
        costPer1kOutput: 0.0044,
      },
      {
        id: "o3",
        name: "o3",
        contextWindow: 200_000,
        maxOutput: 100_000,
        costPer1kInput: 0.002,
        costPer1kOutput: 0.008,
      },
    ],
    defaultModel: "gpt-5.3-codex",
    requiresApiKey: true,
    installCommand: "npm install -g @openai/codex",
    checkCommand: "codex --version",
  },
  "gemini-cli": {
    id: "gemini-cli",
    name: "gemini-cli",
    displayName: "Gemini CLI",
    icon: "google",
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        contextWindow: 1_000_000,
        maxOutput: 65_536,
        costPer1kInput: 0.00125,
        costPer1kOutput: 0.01,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        contextWindow: 1_000_000,
        maxOutput: 65_536,
        costPer1kInput: 0.0003,
        costPer1kOutput: 0.0025,
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash Lite",
        contextWindow: 1_000_000,
        maxOutput: 65_536,
        costPer1kInput: 0.0001,
        costPer1kOutput: 0.0004,
      },
    ],
    defaultModel: "gemini-2.5-pro",
    requiresApiKey: true,
    installCommand: "npm install -g @google/gemini-cli",
    checkCommand: "gemini --version",
  },
  deepseek: {
    id: "deepseek",
    name: "deepseek",
    displayName: "DeepSeek",
    icon: "deepseek",
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek V3.2 Chat",
        contextWindow: 128_000,
        maxOutput: 8_192,
        costPer1kInput: 0.00028,
        costPer1kOutput: 0.00042,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek V3.2 Reasoner",
        contextWindow: 128_000,
        maxOutput: 64_000,
        costPer1kInput: 0.00028,
        costPer1kOutput: 0.00042,
      },
    ],
    defaultModel: "deepseek-chat",
    requiresApiKey: true,
    installCommand: "pip install deepseek-coder",
    checkCommand: "deepseek --version",
  },
  openclaw: {
    id: "openclaw",
    name: "openclaw",
    displayName: "OpenClaw",
    icon: "openclaw",
    models: [
      {
        id: "openclaw-local",
        name: "OpenClaw (Local Docker)",
        contextWindow: 32_000,
        maxOutput: 8_192,
        costPer1kInput: 0,
        costPer1kOutput: 0,
      },
    ],
    defaultModel: "openclaw-local",
    requiresApiKey: false,
    installCommand: "docker pull openclaw/openclaw:latest",
    checkCommand: "docker inspect openclaw/openclaw:latest",
  },
  shell: {
    id: "shell",
    name: "shell",
    displayName: "Terminal",
    icon: "terminal",
    models: [
      {
        id: "bash",
        name: "Bash Shell",
        contextWindow: 0,
        maxOutput: 0,
        costPer1kInput: 0,
        costPer1kOutput: 0,
      },
    ],
    defaultModel: "bash",
    requiresApiKey: false,
    installCommand: "",
    checkCommand: "bash --version",
  },
};
